---
sahara:
  enabled: False
  sahara_url: http://tarballs.openstack.org/sahara/sahara-stable-kilo.tar.gz
  dashboard_url: http://tarballs.openstack.org/sahara-dashboard/sahara-dashboard-master.tar.gz
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"

  logs:
    - paths:
        - /var/log/sahara/sahara-all.log

  logging:
    debug: False
    verbose: False
