---
stack_env: vagrant-allinone
floating_ip: 10.1.1.100

xtradb:
  sst_auth_password: asdf

percona:
  replication: False

nova:
  scheduler_default_filters: AvailabilityZoneFilter,ComputeFilter

ironic:
  enabled: True
  tftp_server: 172.16.255.100
  dns_server: 172.16.255.100
  api_url:
    scheme: http
    host: 172.16.255.100
    port: 6385

neutron:
  dhcp_dns_servers:
    - 172.16.255.100
