---
- name: remove older libruby
  apt: pkg=libruby1.8 purge=yes state=absent

- name: install system tools
  apt: pkg={{ item }}
  with_items:
    - ack-grep
    - build-essential
    - curl
    - dstat
    - ethtool
    - git
    - htop
    - iotop
    - iperf
    - ltrace
    - mcelog
    - mtr
    - netcat
    - pstack
    - pv
    - smem
    - socat
    - tree
    - vim
    - cdpr
    - sysstat
    - logrotate
