---
- name: neutron networks
  neutron_network: name={{ item.name }}
                   provider_network_type={{ item.network_type }}
                   state=present
                   shared={{ item.shared }}
                   router_external={{ item.external }}
                   provider_segmentation_id={{ item.segmentation_id }}
                   provider_physical_network={{ item.provider_physical_network }}
                   auth_url={{ endpoints.auth_uri }}
                   login_tenant_name=admin
                   login_username=provider_admin
                   login_password={{ secrets.provider_admin_password }}
  with_items: neutron.networks
  run_once: true

- name: neutron subnets
  neutron_subnet: name={{ item.name }}
                  network_name={{ item.network_name }}
                  cidr={{ item.cidr }}
                  enable_dhcp={{ item.enable_dhcp }}
                  gateway_ip={{ item.gateway_ip }}
                  ip_version={{ item.ip_version }}
                  dns_nameservers={{ neutron.tenant_nameservers|join(',') }}
                  state=present
                  auth_url={{ endpoints.auth_uri }}
                  login_tenant_name=admin
                  login_username=provider_admin
                  login_password={{ secrets.provider_admin_password }}
  with_items: neutron.subnets
  run_once: true

- name: neutron routers
  neutron_router: state=present
                  name={{ item.name }}
                  tenant_name={{ item.tenant_name }}
                  admin_state_up=true
                  auth_url={{ endpoints.auth_uri }}
                  login_tenant_name=admin
                  login_username=provider_admin
                  login_password={{ secrets.provider_admin_password }}
  with_items: neutron.routers
  run_once: true

- name: neutron routers gateways
  neutron_router_gateway: state=present
                          router_name={{ item.name }}
                          network_name=external
                          auth_url={{ endpoints.auth_uri }}
                          login_tenant_name=admin
                          login_username=provider_admin
                          login_password={{ secrets.provider_admin_password }}
  with_items: neutron.routers
  run_once: true

- name: neutron router interfaces
  neutron_router_interface: router_name={{ item.router_name }}
                            subnet_name={{ item.subnet_name }}
                            tenant_name={{ item.tenant_name }}
                            state=present
                            auth_url={{ endpoints.auth_uri }}
                            login_tenant_name=admin
                            login_username=provider_admin
                            login_password={{ secrets.provider_admin_password }}
  with_items: neutron.router_interfaces
  run_once: true

- name: determine Neutron external interface name
  neutron_network: name=external
                   auth_url=https://{{ endpoints.main }}:5001/v2.0/
                   login_tenant_name=admin
                   login_username=provider_admin
                   login_password={{ secrets.provider_admin_password }}
  register: result
  run_once: true

- name: set neutron interface fact
  set_fact: neutron_external_interface=brq{{ result.id|truncate(length=11,killwords=true,end='') }}

- name: neutron external interface config
  template: src=neutron_external_interface.cfg
            dest=/etc/network/interfaces.d/{{ neutron_external_interface }}.cfg
            owner=root group=root mode=0644
  notify: ifup neutron external interface
